language: generic
sudo: required
before_install:
  - npm install
  - export NODE_ENV=testing
install:
  - pip install requests[security]
  - pip install --user -r requirements.txt
node_js:
  - '8'
python:
  - '2.7.15'
  - '3.6'
services:
  - mongodb
script: 
  - npm run lint
  - npm run integration-test
  - npm run unit-test
notifications:
  slack: bwekfastclub:apMLylCPCrM8rZTKlRkUOohL
