language: node_js
node_js:
  - '8'
before_install:
  - export NODE_ENV=testing
sudo: required
services:
  - mongodb
script: 
  - npm run lint
  - npm run integration-test
  - npm run unit-test
notifications:
  slack: bwekfastclub:apMLylCPCrM8rZTKlRkUOohL
